DEL/DEL.UI/Controllers/ChartController.cs
using DEL.UI.Logic;
using DEL.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DEL.UI.Controllers
{
    public class ChartController : Controller
    {
        public ViewResult Index()
        {
            return View();
        }

        public ViewResult Type1()
        {
            return View(new ChartModel());
        }

        public ViewResult Type2()
        {
            return View(new ChartModel());
        }

        public ViewResult Type3()
        {
            return View(new ChartModel());
        }
    }
}

DEL/DEL.UI/Views/Chart/Index.cshtml
@{
    ViewBag.Title = "Dział Ewidencji Ludności - zestawienia danych";
}

<h1 class="heading-bg p-1 mb-3">Zestawienia danych</h1>

<div class="row justify-content-between">
    <div class="col-lg-12 col-12 p-4 py-0">
        <div class="row justify-content-around">

            <a href="@Url.Action("Type1", "Chart")" class="col-lg-5 col-12 p-3 my-3 portal-box bg-pic-2 blockLink">
                <h1 class="mt-4">Według wieku</h1>
                <hr />
                <h6 class="mb-5">Wykres słupkowy, przedstawiający relację wieku i liczby ludności.</h6>
            </a>
            <a href="@Url.Action("Type2", "Chart")" class="col-lg-5 col-12 p-3 my-3 portal-box bg-pic-7 blockLink">
                <h1 class="mt-4">Przyrost naturalny</h1>
                <hr />
                <h6 class="mb-5">Liczba urodzeń i zgonów według wieku - wykres słupkowy.</h6>
            </a>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12 col-12 px-md-5 py-md-3">
        <div class="col-lg-1 col-0"></div>
        <a href="@Url.Action("Type3", "Chart")" class="col-lg-12 col-12 p-3 my-3 portal-box bg-pic-6 blockLink">
            <h1 class="mt-4">Społeczeństwo</h1>
            <hr />
            <h6 class="mb-5">Ogólne zestawienie na temat ludności.</h6>
        </a>
        <div class="col-lg-1 col-0"></div>

    </div>
</div>

DEL/DEL.UI/Views/Chart/Type1.cshtml
@using DEL.UI.Models
@model ChartModel
@{
    ViewBag.Title = "Dział Ewidencji Ludności - zestawienia danych";
}

<h1 class="heading-bg p-1 mb-3">Zestawienie ludności według wieku</h1>

<canvas id="chart" width="500" height="250"></canvas>
<hr />
<a id="link" class="btn btn-lg btn-outline-danger mb-5 w-100"><i class="fas fa-download"></i> Zapisz wykres do pliku</a>

<script src="~/Content/Chart.min.js"></script>
<script>
    var ctx = document.getElementById('chart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'bar',
        data: {
            labels: @Html.Raw(Json.Encode(Model.AgeArray)),
            datasets: [{
                label: 'Liczba ludności',
                data: @Html.Raw(Json.Encode(Model.PopulationByAge)),
                borderWidth: 1
            }]
        },
        options: {
            animation: {
                duration: 0 // general animation time
            },
            hover: {
                animationDuration: 0 // duration of animations when hovering an item
            },
            responsiveAnimationDuration: 0, // animation duration after a resize
            scales: {
                
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

    setTimeout(function () {
        var canvas = document.getElementById('chart');
        var link = document.getElementById('link');
        link.href = canvas.toDataURL();
        link.download = "zestawienie.png";
    }, 2000);
</script>

DEL/DEL.UI/Views/Chart/Type2.cshtml
@using DEL.UI.Models
@model ChartModel
@{
    ViewBag.Title = "Dział Ewidencji Ludności - zestawienia danych";
}

<h1 class="heading-bg p-1 mb-3">Przyrost naturalny</h1>

<canvas id="chart" width="500" height="250"></canvas>
<hr />
<a id="link" class="btn btn-lg btn-outline-danger mb-5 w-100"><i class="fas fa-download"></i> Zapisz wykres do pliku</a>

<script src="~/Content/Chart.min.js"></script>
<script>
    var ctx = document.getElementById('chart').getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'line',
        data: {
            labels: @Html.Raw(Json.Encode(Model.YearArray)),
            datasets: [{
                label: 'Urodzenia',
                data: @Html.Raw(Json.Encode(Model.BirthsByYear)),
                fill: false,
                borderColor: 'rgba(46, 204, 64, 1)'
            },
            {
                label: 'Zgony',
                data: @Html.Raw(Json.Encode(Model.DeathsByYear)),
                fill: false,
                borderColor: 'rgba(212, 33, 61, 1)'
            }]
        },
        options: {
            animation: {
                duration: 0
            },
            hover: {
                animationDuration: 0
            },
            responsiveAnimationDuration: 0,
            scales: {

                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });

    setTimeout(function () {
        var canvas = document.getElementById('chart');
        var link = document.getElementById('link');
        link.href = canvas.toDataURL();
        link.download = "zestawienie.png";
    }, 2000);
</script>

DEL/DEL.UI/Views/Chart/Type3.cshtml
@using DEL.UI.Models
@model ChartModel
@{
    ViewBag.Title = "Dział Ewidencji Ludności - zestawienia danych";
}

<h1 class="heading-bg p-1 mb-3">Zestawienie danych o społeczeństwie</h1>

<div class="row mb-3">
    <div class="col-lg-4 col-12">
        <canvas id="chart1" width="500" height="500"></canvas>
    </div>
    <div class="col-lg-4 col-12">
        <canvas id="chart2" width="500" height="500"></canvas>
    </div>
    <div class="col-lg-4 col-12">
        <canvas id="chart3" width="500" height="500"></canvas>
    </div>
</div>

<hr />
<div class="row">
    <div class="col-lg-4 col-12">
        <a id="link1" class="btn btn-lg btn-outline-danger mb-5 w-100"><i class="fas fa-download"></i> Zapisz wykres do pliku</a>
    </div>
    <div class="col-lg-4 col-12">
        <a id="link2" class="btn btn-lg btn-outline-danger mb-5 w-100"><i class="fas fa-download"></i> Zapisz wykres do pliku</a>
    </div>
    <div class="col-lg-4 col-12">
        <a id="link3" class="btn btn-lg btn-outline-danger mb-5 w-100"><i class="fas fa-download"></i> Zapisz wykres do pliku</a>
    </div>
</div>

<script src="~/Content/Chart.min.js"></script>
<script>
    var ctx1 = document.getElementById('chart1').getContext('2d');
    var ctx2 = document.getElementById('chart2').getContext('2d');
    var ctx3 = document.getElementById('chart3').getContext('2d');

    var chart1 = new Chart(ctx1, {
        type: 'doughnut',
        data: {
            labels: ["Mężczyźni", "Kobiety"],
            datasets: [{
                data: [@Model.Males, @Model.Females],
                borderColor: 'rgba(255, 255, 255, 1)',
                borderWidth: 2,
                backgroundColor: [
                    'rgba(54, 162, 235, 1)',
                    'rgba(255, 99, 132, 1)'
                ],
            }]
        }
    });

        var chart2 = new Chart(ctx2, {
        type: 'doughnut',
        data: {
            labels: ["Wolni", "W związku"],
            datasets: [{
                data: [@Model.Free, @Model.Married],
                borderColor: 'rgba(255, 255, 255, 1)',
                borderWidth: 2,
                backgroundColor: [
                    'rgba(57, 204, 204, 1)',
                    'rgba(177, 13, 201, 1)'
                ],
            }]
        }
    });

        var chart3 = new Chart(ctx3, {
        type: 'doughnut',
        data: {
            labels: ["<18 lat", "18-65 lat", ">65 lat"],
            datasets: [{
                data: [@Model.Young, @Model.Middle, @Model.Old],
                borderColor: 'rgba(255, 255, 255, 1)',
                borderWidth: 2,
                backgroundColor: [
                    'rgba(46, 204, 64, 1)',
                    'rgba(255, 220, 0, 1)',
                    'rgba(255, 133, 27, 1)'
                ],
            }]
        }
    });

    setTimeout(function () {
        var canvas1 = document.getElementById('chart1');
        var canvas2 = document.getElementById('chart2');
        var canvas3 = document.getElementById('chart3');
        var link1 = document.getElementById('link1');
        link1.href = canvas1.toDataURL();
        link1.download = "zestawienie.png";
        var link2 = document.getElementById('link2');
        link2.href = canvas2.toDataURL();
        link2.download = "zestawienie.png";
        var link3 = document.getElementById('link3');
        link3.href = canvas2.toDataURL();
        link3.download = "zestawienie.png";
    }, 2000);
</script>