DEL/DEL.UI/Controllers/LoginController.cs
using DEL.UI.Authentication;
using DEL.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Principal;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace DEL.UI.Controllers
{
    /// <summary>
    /// Kontroler do logowania.
    /// </summary>
    public class LoginController : Controller
    {
        /// <summary>
        /// Otwiera stronę logowania.
        /// </summary>
        public virtual ActionResult Index()
        {
            return View(new Login());
        }

        /// <summary>
        /// Loguje użytkownika.
        /// </summary>
        /// <param name="model">Model.</param>
        [HttpPost]
        public virtual ActionResult Index(Login model)
        {
            Authenticate(model);
            return View(model);
        }

        /// <summary>
        /// Autentykuje przekazany model.
        /// </summary>
        /// <param name="model">Model.</param>
        /// <param name="redirect">Jeżeli true, przekierowuje po zalogowaniu użytkownika na stronę główną.</param>
        /// <returns>true jeśli model zostaje zautentykowany, w przeciwnym razie false.</returns>
        protected virtual bool Authenticate(Login model, bool redirect = true)
        {
            bool authenticated = FormsAuthentication.Authenticate(model.UserName, model.Password);

            if (!authenticated)
            {
                return false;
            }

            var user = new GenericIdentity(model.UserName);
            var principal = new SimpleConfigurationPrincipal(user);
            SimpleConfigurationPrincipal.SetAuthenticatedPrincipal(principal);

            if (redirect)
            {
                FormsAuthentication.RedirectFromLoginPage(model.UserName, false);
            }

            return true;
        }

        /// <summary>
        /// Wylogowuje użytkownika.
        /// </summary>
        public virtual ActionResult Logoff()
        {
            Session.Abandon();
            FormsAuthentication.SignOut();
            FormsAuthentication.RedirectToLoginPage();
            return RedirectToAction("Index");
        }
    }
}

DEL/DEL.UI/Controllers/NewsController.cs
using DEL.UI.Logic;
using DEL.UI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DEL.UI.Controllers
{
    public class NewsController : Controller
    {
        [HttpGet]
        public ActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Add(News model)
        {
            model.Date = DateTime.Now;
            model.Author = System.Web.HttpContext.Current.User.Identity.Name;

            if (ModelState.IsValid)
            {
                var result = new ApiClient().PostData<News>("api/news", model);
                return RedirectToAction("Index", "Home");
            }
            return View(model);
        }

        [HttpGet]
        public ViewResult Delete(News model)
        {
            return View(model);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAction(News model)
        {
            bool result = new ApiClient().DeleteData("api/news", model);
            return RedirectToAction("Index", "Home");
        }
    }
}

DEL/DEL.UI/Views/Shared/_Layout.cshtml
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="~/Content/favicon.ico">

    <link href="~/Content/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/fa/css/all.min.css" rel="stylesheet">
    <link href="~/Content/jquery-ui.min.css" rel="stylesheet">
    <link href="~/Content/site.css" rel="stylesheet">
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-md fixed-top bg-poland-red">
            <a href="@Url.Action("Index", "Home")" class="navbar-brand font-weight-bold">
                <img alt="Dział Ewidencji ludności" src="@Url.Content("~/Content/img/logo.png")" class="header-logo">
            </a>
            <a href="@Url.Action("Add", "News" )" class="btn btn-lg btn-outline-light ml-auto"><i class="fas fa-plus-square"></i> Dodaj wiadomość</a>
            <a href="@Url.Action("Logoff", "Login")" class="btn btn-lg btn-outline-light ml-3"><i class="fas fa-sign-out-alt"></i> Wyloguj</a>
        </nav>
    </header>

    <main role="main" class="container">
        @RenderBody()
    </main>

    <footer class="footer">
        <div class="container">
            <span class="text-muted text-center"><span class="font-weight-bold">&copy; 2019</span> Dział Ewidencji Ludności | ul. Statystyczna 1, 00-999 Warszawa</span>
        </div>
    </footer>


    <script src="~/Content/jquery-3.4.1.min.js"></script>
    <script src="~/Content/jquery-ui.min.js"></script>
    <script>window.jQuery || document.write('<script src="~/Content/jquery-3.4.1.min.js"><\/script>')</script>
    <script src="~/Content/popper.min.js"></script>
    <script src="~/Content/bootstrap/js/bootstrap.min.js"></script>
   

    <script>
        $(function () {
            $("#datepickerBirth, #datepickerDeath").datepicker({
                dateFormat: "dd.mm.yy",
                changeMonth: true,
                changeYear: true,
                yearRange: "-120:+0"
            });
        });

        $(function () {
            $('#Death').change(function () {
                $('#death-div').toggle(this.checked);
            }).change();
        });

        $(function () {
            $('#Death').change(function () {
                $('#death-div-2').toggle(!this.checked);
            }).change();
        });

        $(function () {
            $('#Married').change(function () {
                $('#spouse-div').toggle(this.checked);
            }).change();
        });
    </script>
</body>